version: 2.1

executors:
    python-36:
      docker:
        - image: circleci/python:3.6.6-stretch
    python-37:
      docker:
        - image: circleci/python:3.7.5-buster

orbs:
  codecov: codecov/codecov@1.0.4

build:
  steps:
    - &install_dependencies_step
      run:
        name: Install dependencies
        command: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          make setup
          pip3 install codecov==2.0.15

    - &lint_step
      run:
        name: Running Static Code Analysis
        command: |
          . .venv/bin/activate
          make lint
    - &unit_step
      run:
        name: Running Unit Tests
        command: |
          . .venv/bin/activate
          make test
    - &restore_cache-py36
      restore_cache:
        keys:
          - v1-dependencies-python_3.6.6-{{ checksum "requirements-test.txt" }}-{{ checksum "setup.py" }}
    - &restore_cache-py37
      restore_cache:
        keys:
          - v1-dependencies-python_3.7.5-{{ checksum "requirements-test.txt" }}-{{ checksum "setup.py" }}
    - &save_cache
        save_cache:
          paths:
            - .venv
defaults: &defaults
  working_directory: ~/platform-notifications



jobs:

  test-py36:
    <<: *defaults
    executor: python-36
    steps:
      - checkout
      - *restore_cache-py36
      - *install_dependencies_step
      - *save_cache
      - *lint_step
      - *unit_step
      - codecov/upload:
          file: .coverage.xml
          flags: py36
  test-py37:
    <<: *defaults
    executor: python-37
    steps:
      - checkout
      - *restore_cache-py37
      - *install_dependencies_step
      - *save_cache
      - *lint_step
      - *unit_step
      - codecov/upload:
          file: .coverage.xml
          flags: py37

  devpi_deploy:
    <<: *defaults
    executor: python-3.7
    steps:
      - checkout
      - restore_cache:
          keys:
          - &cache_key_devpi v1-dependencies-python_3.6.6-devpi-{{ checksum "setup.py" }}
      - run:
          name: Setup venv
          command: |
            python3 -m venv venv
      - run:
          name: devpi setup
          command: |
            . venv/bin/activate
            make -s devpi_setup
      - run:
          name: devpi upload
          command: |
            . venv/bin/activate
            make devpi_upload
      - save_cache:
          paths:
            - venv
          key: *cache_key_devpi



workflows:
  version: 2

  main:
    jobs:
      - test-py36:
          context: org-dev
      - test-py37:
          context: org-dev
  devpi:
    jobs:
      - test-py36:
          context: org-dev
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - test-py37:
          context: org-dev
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - devpi_deploy:
          context: org-dev
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - test-py36
            - test-py37
